vscode:
  extensions:
    - aliariff.auto-add-brackets
    - aaron-bond.better-comments
    - streetsidesoftware.code-spell-checker
    - serayuzgur.crates
    - ms-azuretools.vscode-docker
    - usernamehw.errorlens
    - tamasfe.even-better-toml
    - file-icons.file-icons
    - donjayamanne.githistory
    - eamodio.gitlens
    - oderwat.indent-rainbow
    - DavidAnson.vscode-markdownlint
    - ionutvmi.path-autocomplete
    - christian-kohler.path-intellisense
    - esbenp.prettier-vscode
    - mechatroner.rainbow-csv
    - pinage404.rust-extension-pack
    - Swellaby.rust-pack
    - Swellaby.vscode-rust-test-adapter
    - rust-lang.rust-analyzer
    - sourcery.sourcery
    - hbenl.test-adapter-converter
    - hbenl.vscode-test-explorer
    - wayou.vscode-todo-highlight
    - Gruntfuggly.todo-tree
    - Equinusocio.vsc-material-theme
